jobs:
- job: Default
  timeoutInMinutes: 60
  pool:
    vmImage: Ubuntu-16.04

  # don't build on PRs
  condition: ne(variables['Build.Reason'], 'PullRequest')
  steps:

  - bash: .ci/setup.sh
    displayName: 'Setup'

  - bash: .ci/build.sh
    displayName: 'Build'
    env:
      GITHUB_API_KEY: $(GITHUB_API_KEY)
